name: Deploy Code

on:
   workflow_run:
     workflows: ["Run Tests"]
     types: [completed] #requested

jobs:
   deploy:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Setup Python 3.11
         uses: actions/setup-python@v3
         with:
          python-version: '3.11.0'
       - name: Install Dependencies
         run: pip install -r requirements.txt
       - name: Executing remote ssh commands using ssh key
         uses: appleboy/ssh-action@v0.1.10
         #uses: ./
         with:
           host: 68.183.15.232
           username: root
           key: ${{ secrets.KEY }}
           port: 22
           #script: whoami
           #script: ./deploy_files.sh
           #script: |
           # echo "Get files from Main"
           # echo ${{ github.workspace }}/main.py
           # cat ${{ github.workspace }}/main.py
           #script: sh /home/cd_assignment/deploy_files.sh
           script: pwd
